const fs = require('fs');
const path = require('path');

const REGIONAL_RECORDS = [
  // =========================================================================
  // DISTRICT 1: TIRUNELVELI (Nellai) — Main Roads, Highways, Corridors & Villages
  // =========================================================================
  {
    reportId: 'RPT-TNV-001',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.7138,
    longitude: 77.7568,
    address: 'South Bypass Highway Junction (NH-44), Near Thamirabarani Bridge Turning, Tirunelveli',
    description: 'Adult street dog struck by speeding four-wheeler while crossing the four-lane bypass junction at dusk.',
    possibleCauses: ['High vehicle speed', 'Poor street lighting', 'Animals frequently crossing this road'],
    citizenObservation: 'Vehicles take the bypass curve at excessive speeds; stray dogs regularly cross from the river bank.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-01T18:45:00.000Z'
  },
  {
    reportId: 'RPT-TNV-002',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.7141,
    longitude: 77.7570,
    address: 'South Bypass Corridor, 100m North of Highway Toll Approach, Palayamkottai, Tirunelveli',
    description: 'Puppy hit by two-wheeler, stranded on the highway median strip barrier.',
    possibleCauses: ['Poor traffic control', 'High vehicle speed'],
    citizenObservation: 'Broken median concrete barrier allows stray dogs to wander directly into highway express lanes.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-02T11:20:00.000Z'
  },
  {
    reportId: 'RPT-TNV-003',
    district: 'Tirunelveli',
    animalType: 'Cattle',
    latitude: 8.7136,
    longitude: 77.7565,
    address: 'NH-44 Underpass Entry, South Bypass Junction, Tirunelveli',
    description: 'Milch cow hit by heavy commercial container truck during night hours with poor visibility.',
    possibleCauses: ['Road obstruction', 'Poor street lighting', 'Garbage/food attracting animals'],
    citizenObservation: 'Lack of functional high-mast lighting makes grazing cows invisible on the curve after sunset.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-03T20:15:00.000Z'
  },
  {
    reportId: 'RPT-TNV-004',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.7275,
    longitude: 77.7126,
    address: 'Tirunelveli Railway Junction Road, Near Madurai Road Roundabout, Tirunelveli',
    description: 'Street dog collided with auto-rickshaw navigating crowded junction roundabout.',
    possibleCauses: ['Heavy traffic/noise', 'Poor traffic control'],
    citizenObservation: 'Heavy passenger transit and auto traffic disorients stray animals near the station front.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-04T09:30:00.000Z'
  },
  {
    reportId: 'RPT-TNV-005',
    district: 'Tirunelveli',
    animalType: 'Cat',
    latitude: 8.7230,
    longitude: 77.7280,
    address: 'Vannarpettai Sulochana Mudaliar Bridge Approach, Tirunelveli',
    description: 'Cat brushed by two-wheeler on the bridge incline footpath.',
    possibleCauses: ['High vehicle speed', 'Poor street lighting'],
    citizenObservation: 'Bikes race across the Thamirabarani bridge ramp with no speed breakers.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.94,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-05T22:10:00.000Z'
  },
  {
    reportId: 'RPT-TNV-006',
    district: 'Tirunelveli',
    animalType: 'Cattle',
    latitude: 8.7186,
    longitude: 77.7424,
    address: 'Palayamkottai Gandhi Market Road, Near St. Xavier College, Palayamkottai, Tirunelveli',
    description: 'Stray bull hit by delivery van near vegetable market disposal area.',
    possibleCauses: ['Garbage/food attracting animals', 'Poor road visibility'],
    citizenObservation: 'Vegetable waste left on road margins attracts stray cattle herd causing vehicular blockades.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-06T17:40:00.000Z'
  },
  {
    reportId: 'RPT-TNV-007',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.7450,
    longitude: 77.7180,
    address: 'Thachanallur National Highway (NH-44) Bypass Curve, Tirunelveli',
    description: 'Community dog struck by omni bus entering the city from Madurai highway.',
    possibleCauses: ['High vehicle speed', 'Poor road visibility'],
    citizenObservation: 'Long-distance buses maintain high speeds as they descend into the Thachanallur bypass ramp.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-07T21:15:00.000Z'
  },
  {
    reportId: 'RPT-TNV-008',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.7050,
    longitude: 77.7340,
    address: 'Melapalayam High Road, Near Bazaar Mosque Junction, Tirunelveli',
    description: 'Street dog collided with a delivery motorcycle in narrow commercial street.',
    possibleCauses: ['Vehicles parked near road', 'Heavy traffic/noise'],
    citizenObservation: 'Double parking and heavy auto traffic reduce carriageway visibility.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-08T14:10:00.000Z'
  },
  {
    reportId: 'RPT-TNV-009',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.7200,
    longitude: 77.6750,
    address: 'Pettai Industrial Estate Main Road (SH-40), Pettai, Tirunelveli',
    description: 'Factory watchdog wandered into industrial transit lane and got brushed by lorry.',
    possibleCauses: ['Poor street lighting', 'Road obstruction'],
    citizenObservation: 'Heavy raw material trucks enter and exit Pettai SIDCO area with zero illumination.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.94,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-09T19:00:00.000Z'
  },
  {
    reportId: 'RPT-TNV-010',
    district: 'Tirunelveli',
    animalType: 'Cattle',
    latitude: 8.8520,
    longitude: 77.7810,
    address: 'Gangaikondan SIPCOT Industrial Park NH-44 Crossing, Gangaikondan Village, Tirunelveli',
    description: 'Cow grazing on highway median vegetation struck by express goods container.',
    possibleCauses: ['High vehicle speed', 'Animals frequently crossing this road'],
    citizenObservation: 'Dairy farmers allow cattle to graze on highway median grass along Gangaikondan stretch.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-10T06:45:00.000Z'
  },
  {
    reportId: 'RPT-TNV-011',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.6830,
    longitude: 77.5620,
    address: 'Cheranmahadevi Main Road (SH-40), Near Thamirabarani Canal, Cheranmahadevi, Tirunelveli',
    description: 'Village dog struck by state transport bus on narrow rural highway bend.',
    possibleCauses: ['Road obstruction', 'Poor road visibility'],
    citizenObservation: 'Sharp blind turns with dense tamarind tree cover obstruct driver view.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-11T16:20:00.000Z'
  },
  {
    reportId: 'RPT-TNV-012',
    district: 'Tirunelveli',
    animalType: 'Cattle',
    latitude: 8.7050,
    longitude: 77.4580,
    address: 'Ambasamudram - Tenkasi Highway, Near Tilak Vidyalaya, Ambasamudram, Tirunelveli',
    description: 'Stray cow hit by tourist car driving towards Courtallam.',
    possibleCauses: ['High vehicle speed', 'Animals frequently crossing this road'],
    citizenObservation: 'Tourist season traffic moves fast through town corridors without observing cattle warning boards.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-12T18:30:00.000Z'
  },
  {
    reportId: 'RPT-TNV-013',
    district: 'Tirunelveli',
    animalType: 'Cat',
    latitude: 8.6920,
    longitude: 77.4610,
    address: 'Kallidaikurichi Agasthiyar Temple Road, Near Railway Crossing, Kallidaikurichi, Tirunelveli',
    description: 'Cat hit by motorcycle crossing closed railway gate bypass.',
    possibleCauses: ['Poor street lighting', 'Poor road visibility'],
    citizenObservation: 'Poorly lit railway track approaches cause minor roadkill hazards.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.93,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-13T20:50:00.000Z'
  },
  {
    reportId: 'RPT-TNV-014',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.4890,
    longitude: 77.6620,
    address: 'Nanguneri Special Economic Zone NH-44 Toll Approach, Nanguneri, Tirunelveli',
    description: 'Stray dog hit at high speed near the toll lane deceleration zone.',
    possibleCauses: ['High vehicle speed', 'Lack of animal crossing signage'],
    citizenObservation: 'Highways approaching the toll booth have open fence gaps where stray dogs cross.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-14T07:15:00.000Z'
  },
  {
    reportId: 'RPT-TNV-015',
    district: 'Tirunelveli',
    animalType: 'Cattle',
    latitude: 8.3810,
    longitude: 77.6180,
    address: 'Vallioor New Bus Stand NH-44 Junction, Vallioor Village, Tirunelveli',
    description: 'Cow struck by interstate tourist bus at Vallioor junction.',
    possibleCauses: ['Poor traffic control', 'Garbage/food attracting animals'],
    citizenObservation: 'Market dumps near Vallioor bus stand attract domestic animals onto the highway lanes.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-14T19:25:00.000Z'
  },
  {
    reportId: 'RPT-TNV-016',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.3240,
    longitude: 77.5810,
    address: 'Panagudi Windmill Farm Corridor Road, Panagudi Village, Tirunelveli',
    description: 'Shepherd dog hit by maintenance pickup truck near windmill substation.',
    possibleCauses: ['High vehicle speed', 'Poor road visibility'],
    citizenObservation: 'Dusty access roads and strong crosswinds reduce hearing warning for animals.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-15T15:00:00.000Z'
  },
  {
    reportId: 'RPT-TNV-017',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.5130,
    longitude: 77.5520,
    address: 'Kalakkad Mundanthurai Wildlife Sanctuary Buffer Road, Kalakkad, Tirunelveli',
    description: 'Stray dog struck by tourist vehicle on foothills approach road.',
    possibleCauses: ['Animals frequently crossing this road', 'High vehicle speed'],
    citizenObservation: 'High speed movement of visitors into the buffer zone requires rumble strips.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-16T12:40:00.000Z'
  },
  {
    reportId: 'RPT-TNV-018',
    district: 'Tirunelveli',
    animalType: 'Cat',
    latitude: 8.8410,
    longitude: 77.6430,
    address: 'Manur Lake Bund Road, Near Manur Police Station, Manur Village, Tirunelveli',
    description: 'Cat hit on narrow canal bridge culvert by tractor.',
    possibleCauses: ['Poor street lighting', 'Road obstruction'],
    citizenObservation: 'Unfenced culvert bridge lacks street lighting at night.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.92,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-17T21:00:00.000Z'
  },
  {
    reportId: 'RPT-TNV-019',
    district: 'Tirunelveli',
    animalType: 'Dog',
    latitude: 8.6810,
    longitude: 77.7450,
    address: 'Reddiarpatti Hill Road Intersection, Reddiarpatti Village, Tirunelveli',
    description: 'Dog hit by tipper lorry carrying quarry gravel.',
    possibleCauses: ['High vehicle speed', 'Poor road visibility'],
    citizenObservation: 'Heavy gravel lorries drive aggressively on this village link road.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-18T10:15:00.000Z'
  },
  {
    reportId: 'RPT-TNV-020',
    district: 'Tirunelveli',
    animalType: 'Cattle',
    latitude: 8.6940,
    longitude: 77.6180,
    address: 'Gopalasamudram Village Agraharam Link Road, Gopalasamudram, Tirunelveli',
    description: 'Cow injured after vehicular impact with water tanker on village bend.',
    possibleCauses: ['Road obstruction', 'Animals frequently crossing this road'],
    citizenObservation: 'Cattle herds cross to the paddy fields twice daily without warning signboards.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-19T08:30:00.000Z'
  },

  // =========================================================================
  // DISTRICT 2: THOOTHUKUDI (Tuticorin) — Port, Highways, Coastal & Village Roads
  // =========================================================================
  {
    reportId: 'RPT-TUT-001',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.7980,
    longitude: 78.1340,
    address: 'Palayamkottai Road, Near VVD Signal Intersection, Thoothukudi City',
    description: 'Street dog run over near central commercial traffic junction during evening rush hour.',
    possibleCauses: ['Heavy traffic/noise', 'Poor traffic control'],
    citizenObservation: 'Heavy traffic entering from Tirunelveli highway creates confusion for animals at VVD signal.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-01T19:10:00.000Z'
  },
  {
    reportId: 'RPT-TUT-002',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.7620,
    longitude: 78.1580,
    address: 'Harbour Express Highway, Near Port Trust Central Gate, Thoothukudi',
    description: 'Stray dog struck by container trailer on the multi-axle port expressway.',
    possibleCauses: ['High vehicle speed', 'Lack of animal crossing signage'],
    citizenObservation: 'Heavy container lorries move at high speed along the open port expressway corridor.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-02T22:45:00.000Z'
  },
  {
    reportId: 'RPT-TUT-003',
    district: 'Thoothukudi',
    animalType: 'Cattle',
    latitude: 8.7750,
    longitude: 78.0820,
    address: 'NH-138 Highway Corridor, Near Korampallam Lake Bridge, Korampallam, Thoothukudi',
    description: 'Grazing bull struck by express bus while crossing the Korampallam lake overbridge.',
    possibleCauses: ['High vehicle speed', 'Poor street lighting', 'Stray cattle grazing on verge'],
    citizenObservation: 'Lake vegetation attracts cattle herds across this busy 4-lane Tirunelveli-Tuticorin highway.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-03T20:30:00.000Z'
  },
  {
    reportId: 'RPT-TUT-004',
    district: 'Thoothukudi',
    animalType: 'Cat',
    latitude: 8.8050,
    longitude: 78.1480,
    address: 'Mattakadai Fish Market Road, Near Old Harbour Road, Thoothukudi',
    description: 'Cat brushed by fish transit tempo near market curb.',
    possibleCauses: ['Garbage/food attracting animals', 'Vehicles parked near road'],
    citizenObservation: 'Fish waste attracts animals directly onto the vehicular road shoulder.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.94,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-04T06:15:00.000Z'
  },
  {
    reportId: 'RPT-TUT-005',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.7120,
    longitude: 78.1480,
    address: 'Mullakadu Industrial Highway, Near SPIC Complex Entry, Mullakadu, Thoothukudi',
    description: 'Factory stray dog collided with chemical tanker truck.',
    possibleCauses: ['Heavy traffic/noise', 'Poor road visibility'],
    citizenObservation: 'Heavy chemical trucks have major blind spots on this industrial stretch.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-05T17:30:00.000Z'
  },
  {
    reportId: 'RPT-TUT-006',
    district: 'Thoothukudi',
    animalType: 'Cattle',
    latitude: 8.7550,
    longitude: 78.0280,
    address: 'NH-138 Highway Bypass, Near Pudukkottai Toll Junction, Pudukkottai Village, Thoothukudi',
    description: 'Cow hit by speeding SUV near village median intersection.',
    possibleCauses: ['High vehicle speed', 'Lack of animal crossing signage'],
    citizenObservation: 'Villagers bring cows across the national highway to graze in nearby drylands.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-06T18:50:00.000Z'
  },
  {
    reportId: 'RPT-TUT-007',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.4980,
    longitude: 78.1250,
    address: 'Tiruchendur Temple Car Street & SH-176 Coastal Road Junction, Tiruchendur, Thoothukudi',
    description: 'Community dog hit by pilgrimage bus near the coastal temple entrance lane.',
    possibleCauses: ['Heavy traffic/noise', 'Poor traffic control'],
    citizenObservation: 'Devotee crowds and tourist buses create congestion and accident hazards for animals.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-07T11:40:00.000Z'
  },
  {
    reportId: 'RPT-TUT-008',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.5680,
    longitude: 78.1340,
    address: 'Kayalpattinam Coastal Bypass Road, Kayalpattinam Village, Thoothukudi',
    description: 'Stray dog brushed by tempo on sand-covered asphalt road.',
    possibleCauses: ['Poor road visibility', 'Road obstruction'],
    citizenObservation: 'Drifting beach sand on road corners causes vehicular skidding.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.94,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-08T15:20:00.000Z'
  },
  {
    reportId: 'RPT-TUT-009',
    district: 'Thoothukudi',
    animalType: 'Cattle',
    latitude: 8.5720,
    longitude: 78.1080,
    address: 'Arumuganeri DCW Chemical Factory Road, Arumuganeri, Thoothukudi',
    description: 'Cow hit by factory supply truck during early evening hours.',
    possibleCauses: ['Poor street lighting', 'Heavy traffic/noise'],
    citizenObservation: 'Factory lorries use high beams which temporarily blind crossing animals.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-09T19:45:00.000Z'
  },
  {
    reportId: 'RPT-TUT-010',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.4050,
    longitude: 78.0580,
    address: 'Kulasekharapatnam ISRO Launch Complex Access Road, Kulasekharapatnam, Thoothukudi',
    description: 'Rural dog hit by construction dumper truck on newly widened road.',
    possibleCauses: ['Construction area', 'High vehicle speed'],
    citizenObservation: 'Rapid infrastructure work for spaceport expansion involves speeding dumper trucks.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-10T14:10:00.000Z'
  },
  {
    reportId: 'RPT-TUT-011',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 9.1720,
    longitude: 77.8680,
    address: 'Kovilpatti NH-44 Bypass Junction, Near Kadalai Mittai Market, Kovilpatti, Thoothukudi',
    description: 'Street dog struck on national highway bypass curve by parcel truck.',
    possibleCauses: ['High vehicle speed', 'Lack of animal crossing signage'],
    citizenObservation: 'Long-distance freight vehicles bypass Kovilpatti at 100+ km/h without slowing down.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-11T22:15:00.000Z'
  },
  {
    reportId: 'RPT-TUT-012',
    district: 'Thoothukudi',
    animalType: 'Cattle',
    latitude: 8.9510,
    longitude: 77.7720,
    address: 'Kayathar NH-44 Toll Road, Near Veerapandiya Kattabomman Memorial, Kayathar, Thoothukudi',
    description: 'Bull grazing on highway median hit by intercity passenger car.',
    possibleCauses: ['High vehicle speed', 'Animals frequently crossing this road'],
    citizenObservation: 'Open median breaks in the Kayathar stretch allow cattle herds onto the express lanes.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-12T07:20:00.000Z'
  },
  {
    reportId: 'RPT-TUT-013',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 9.1480,
    longitude: 77.9950,
    address: 'Ettayapuram Raja Street (SH-38), Near Bharathiyar Memorial House, Ettayapuram, Thoothukudi',
    description: 'Dog hit by two-wheeler in historic palace street.',
    possibleCauses: ['Poor street lighting', 'Vehicles parked near road'],
    citizenObservation: 'Narrow street with tourist parking reduces sightline.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-13T17:30:00.000Z'
  },
  {
    reportId: 'RPT-TUT-014',
    district: 'Thoothukudi',
    animalType: 'Cat',
    latitude: 8.9050,
    longitude: 78.0120,
    address: 'Ottapidaram Taluk Office Road, Ottapidaram Village, Thoothukudi',
    description: 'Cat hit near agricultural canal bridge by tractor.',
    possibleCauses: ['Poor road visibility', 'Road obstruction'],
    citizenObservation: 'Tractors transporting dryland cotton navigate narrow village bridges without lights.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.92,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-14T20:15:00.000Z'
  },
  {
    reportId: 'RPT-TUT-015',
    district: 'Thoothukudi',
    animalType: 'Cattle',
    latitude: 9.1280,
    longitude: 78.1650,
    address: 'Vilathikulam State Highway, Near Chillie Market, Vilathikulam, Thoothukudi',
    description: 'Cow injured after impact with mini-van carrying agricultural harvest.',
    possibleCauses: ['Garbage/food attracting animals', 'High vehicle speed'],
    citizenObservation: 'Harvest seasons cause high truck movements through Vilathikulam village centre.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-15T18:40:00.000Z'
  },
  {
    reportId: 'RPT-TUT-016',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.4410,
    longitude: 77.9120,
    address: 'Sathankulam Main Road, Near Old Bus Stand, Sathankulam, Thoothukudi',
    description: 'Village dog struck by passenger van on market turn.',
    possibleCauses: ['Heavy traffic/noise', 'Poor traffic control'],
    citizenObservation: 'Bus stand intersection lacks pedestrian and animal speed barriers.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-16T13:20:00.000Z'
  },
  {
    reportId: 'RPT-TUT-017',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.4320,
    longitude: 78.0280,
    address: 'Udangudi Thermal Power Plant Road, Udangudi Village, Thoothukudi',
    description: 'Stray dog hit by industrial dump truck transporting coal gravel.',
    possibleCauses: ['Construction area', 'High vehicle speed'],
    citizenObservation: 'Thermal plant construction traffic moves aggressively on coastal link roads.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-17T11:00:00.000Z'
  },
  {
    reportId: 'RPT-TUT-018',
    district: 'Thoothukudi',
    animalType: 'Cat',
    latitude: 8.6250,
    longitude: 78.0850,
    address: 'Authoor Thamirabarani River Bridge Road, Authoor, Thoothukudi',
    description: 'Cat brushed by two-wheeler on wet bridge surface.',
    possibleCauses: ['Poor street lighting', 'Poor road visibility'],
    citizenObservation: 'River mist and lack of lighting make visibility poor across Authoor bridge.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.93,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-18T22:30:00.000Z'
  },
  {
    reportId: 'RPT-TUT-019',
    district: 'Thoothukudi',
    animalType: 'Dog',
    latitude: 8.6350,
    longitude: 78.0250,
    address: 'Eral Vegetable Market Link Road, Eral Village, Thoothukudi',
    description: 'Community dog injured by loading auto reversing into lane.',
    possibleCauses: ['Road obstruction', 'Heavy traffic/noise'],
    citizenObservation: 'Unloading vehicles clutter rural village streets.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-19T09:40:00.000Z'
  },
  {
    reportId: 'RPT-TUT-020',
    district: 'Thoothukudi',
    animalType: 'Cattle',
    latitude: 8.6850,
    longitude: 78.0620,
    address: 'Sawyerpuram Agricultural Road, Near Pope Memorial School, Sawyerpuram, Thoothukudi',
    description: 'Cow hit by speeding milk delivery van in morning hours.',
    possibleCauses: ['Animals frequently crossing this road', 'Poor road visibility'],
    citizenObservation: 'Dense fog in rural agricultural belts obscures crossing cows.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-20T06:20:00.000Z'
  },

  // =========================================================================
  // DISTRICT 3: TENKASI (Extra District) — Foothills, Ghat Roads, Corridors & Villages
  // =========================================================================
  {
    reportId: 'RPT-TSI-001',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 8.9590,
    longitude: 77.3150,
    address: 'Tenkasi New Bus Stand NH-744 Junction, Tenkasi Town',
    description: 'Street dog hit by inter-state bus arriving from Kerala via Kollam highway.',
    possibleCauses: ['Heavy traffic/noise', 'Poor traffic control'],
    citizenObservation: 'Heavy flow of tourist and transport buses at the Tenkasi highway junction.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-01T17:45:00.000Z'
  },
  {
    reportId: 'RPT-TSI-002',
    district: 'Tenkasi',
    animalType: 'Cattle',
    latitude: 8.9320,
    longitude: 77.2750,
    address: 'Courtallam Main Falls Road, Near Old Courtallam Turning, Courtallam, Tenkasi',
    description: 'Milch cow hit by speeding tourist van during southwest monsoon season.',
    possibleCauses: ['High vehicle speed', 'Poor road visibility', 'Animals frequently crossing this road'],
    citizenObservation: 'Wet ghat roads and tourist rush create dangerous blind corners near the falls approach.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-02T19:30:00.000Z'
  },
  {
    reportId: 'RPT-TSI-003',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 8.9280,
    longitude: 77.2550,
    address: 'Five Falls (Aintharuvi) Forest Approach Road, Courtallam, Tenkasi',
    description: 'Dog hit by SUV on narrow mountain stream culvert.',
    possibleCauses: ['Poor street lighting', 'Road obstruction'],
    citizenObservation: 'Zero street lighting along the forest fringe road after 7 PM.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-03T20:10:00.000Z'
  },
  {
    reportId: 'RPT-TSI-004',
    district: 'Tenkasi',
    animalType: 'Cattle',
    latitude: 8.8710,
    longitude: 77.4980,
    address: 'Tirunelveli - Tenkasi 4-Lane Highway (SH-39), Alangulam Market Junction, Alangulam, Tenkasi',
    description: 'Cow hit on highway median cut by speeding delivery truck.',
    possibleCauses: ['High vehicle speed', 'Stray cattle grazing on verge'],
    citizenObservation: 'High speed four-lane traffic between Nellai and Tenkasi gives cattle zero crossing buffer.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-04T18:15:00.000Z'
  },
  {
    reportId: 'RPT-TSI-005',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 8.9120,
    longitude: 77.3850,
    address: 'Pavoorchatram Wholesale Vegetable Market Highway (SH-39), Pavoorchatram, Tenkasi',
    description: 'Market dog run over by vegetable loading lorry at early morning auction.',
    possibleCauses: ['Garbage/food attracting animals', 'Heavy traffic/noise'],
    citizenObservation: 'Huge wholesale vegetable market causes continuous truck loading and dogs scavenging scraps.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-05T05:30:00.000Z'
  },
  {
    reportId: 'RPT-TSI-006',
    district: 'Tenkasi',
    animalType: 'Cat',
    latitude: 8.9780,
    longitude: 77.4250,
    address: 'Surandai Bus Stand Commercial Road, Surandai Town, Tenkasi',
    description: 'Cat brushed by two-wheeler near bus terminus shop row.',
    possibleCauses: ['Poor street lighting', 'Vehicles parked near road'],
    citizenObservation: 'Parked two-wheelers block side vision in market lanes.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.93,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-06T21:40:00.000Z'
  },
  {
    reportId: 'RPT-TSI-007',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 9.0750,
    longitude: 77.3450,
    address: 'NH-744 Kollam - Madurai Highway, Near Kadayanallur Railway Gate, Kadayanallur, Tenkasi',
    description: 'Dog hit by express government bus near railway feeder road.',
    possibleCauses: ['High vehicle speed', 'Poor traffic control'],
    citizenObservation: 'Buses accelerate rapidly after passing the Kadayanallur railway level cross.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-07T14:20:00.000Z'
  },
  {
    reportId: 'RPT-TSI-008',
    district: 'Tenkasi',
    animalType: 'Cattle',
    latitude: 9.1750,
    longitude: 77.4010,
    address: 'NH-744 Lemon Market Corridor, Puliangudi Village, Tenkasi',
    description: 'Stray cow hit by container truck on the national highway.',
    possibleCauses: ['High vehicle speed', 'Garbage/food attracting animals'],
    citizenObservation: 'Cattle roam near roadside wholesale lemon and produce mandis.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.99,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-08T19:00:00.000Z'
  },
  {
    reportId: 'RPT-TSI-009',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 9.2350,
    longitude: 77.4280,
    address: 'Vasudevanallur Border Road (NH-744), Vasudevanallur, Tenkasi',
    description: 'Village dog struck on highway bridge crossing.',
    possibleCauses: ['High vehicle speed', 'Poor road visibility'],
    citizenObservation: 'Speeding vehicles traveling towards Rajapalayam ignore village crossing signboards.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-09T16:15:00.000Z'
  },
  {
    reportId: 'RPT-TSI-010',
    district: 'Tenkasi',
    animalType: 'Cattle',
    latitude: 9.1720,
    longitude: 77.5320,
    address: 'Sankarankovil - Rajapalayam Road, Near Sankaranarayana Swamy Temple Car Street, Sankarankovil, Tenkasi',
    description: 'Temple cow hit by transport bus during monthly festival traffic.',
    possibleCauses: ['Heavy traffic/noise', 'Poor traffic control'],
    citizenObservation: 'Congested temple car streets see high pedestrian and vehicular conflicts with sacred cattle.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-10T12:00:00.000Z'
  },
  {
    reportId: 'RPT-TSI-011',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 8.9850,
    longitude: 77.2480,
    address: 'Shenkottai Western Ghats Road (NH-744), Aryankavu Pass Border, Shenkottai, Tenkasi',
    description: 'Dog struck on hairpin turn descent toward border checkpost.',
    possibleCauses: ['Road obstruction', 'Poor road visibility'],
    citizenObservation: 'Sharp mountain curves with heavy timber and freight lorries.',
    severity: 'Critical',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.97,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-11T21:30:00.000Z'
  },
  {
    reportId: 'RPT-TSI-012',
    district: 'Tenkasi',
    animalType: 'Cat',
    latitude: 8.9750,
    longitude: 77.3420,
    address: 'Ayikudi Amar Seva Sangam Road, Ayikudi Village, Tenkasi',
    description: 'Cat hit near rehabilitation campus entrance lane.',
    possibleCauses: ['Poor street lighting'],
    citizenObservation: 'Village lane lacks street lights at intersection.',
    severity: 'Minor',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.93,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-12T20:10:00.000Z'
  },
  {
    reportId: 'RPT-TSI-013',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 8.9480,
    longitude: 77.4420,
    address: 'Veerakeralampudur Main Road, Near Taluk Office, Veerakeralampudur Village, Tenkasi',
    description: 'Stray dog hit by mini-lorry on rural canal road.',
    possibleCauses: ['High vehicle speed', 'Poor road visibility'],
    citizenObservation: 'Narrow canal bund road lacks speed regulation.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.95,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-13T15:40:00.000Z'
  },
  {
    reportId: 'RPT-TSI-014',
    district: 'Tenkasi',
    animalType: 'Cattle',
    latitude: 8.9880,
    longitude: 77.3820,
    address: 'Sambavar Vadakarai Agricultural Road, Sambavar Vadakarai Village, Tenkasi',
    description: 'Cow hit by tractor trailer returning from sugarcane mill.',
    possibleCauses: ['Animals frequently crossing this road', 'Heavy traffic/noise'],
    citizenObservation: 'Harvest tractors move through narrow village bends during crushing season.',
    severity: 'High',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.98,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-14T18:00:00.000Z'
  },
  {
    reportId: 'RPT-TSI-015',
    district: 'Tenkasi',
    animalType: 'Dog',
    latitude: 8.9450,
    longitude: 77.2950,
    address: 'Ilanji Mango Groves Road (SH-40), Ilanji Village, Tenkasi',
    description: 'Dog brushed by tourist passenger tempo on orchard road.',
    possibleCauses: ['High vehicle speed', 'Poor street lighting'],
    citizenObservation: 'Overhanging tree canopies reduce road lighting during night hours.',
    severity: 'Moderate',
    status: 'COMPLETED',
    remediationStatus: 'PENDING',
    aiConfidence: 0.96,
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    timestamp: '2026-03-15T19:20:00.000Z'
  }
];

function buildFiles() {
  const jsonPath = path.resolve(__dirname, '../../../datasets/animal_roadkill_accidents.json');
  const csvPath = path.resolve(__dirname, '../../../datasets/animal_roadkill_accidents.csv');

  // 1. Write JSON
  fs.writeFileSync(jsonPath, JSON.stringify(REGIONAL_RECORDS, null, 2), 'utf-8');
  console.log(`✅ Generated JSON Dataset: ${jsonPath} (${REGIONAL_RECORDS.length} records)`);

  // 2. Write CSV
  const csvHeaders = ['reportId', 'district', 'animalType', 'latitude', 'longitude', 'address', 'description', 'possibleCauses', 'severity', 'status', 'aiConfidence', 'timestamp'];
  const csvRows = [csvHeaders.join(',')];

  REGIONAL_RECORDS.forEach(r => {
    const causes = (r.possibleCauses || []).join('; ');
    const cleanAddress = `"${(r.address || '').replace(/"/g, '""')}"`;
    const cleanDesc = `"${(r.description || '').replace(/"/g, '""')}"`;
    const cleanCauses = `"${causes.replace(/"/g, '""')}"`;
    csvRows.push([
      r.reportId,
      r.district,
      r.animalType,
      r.latitude,
      r.longitude,
      cleanAddress,
      cleanDesc,
      cleanCauses,
      r.severity,
      r.status,
      r.aiConfidence,
      r.timestamp
    ].join(','));
  });

  fs.writeFileSync(csvPath, csvRows.join('\n'), 'utf-8');
  console.log(`✅ Generated CSV Dataset: ${csvPath} (${csvRows.length - 1} rows)`);
}

buildFiles();
